---
- name: Create server auto_ip
  os_server:
    state: "present"
    cloud: "{{ auth.cloud }}"
    name: "{{ devstack.server_name }}"
    image: "{{ devstack.image }}"
    key_name: "{{ key_name }}"
    timeout: 200
    flavor: "{{ devstack.flavor }}"
    network: "{{ devstack.network }}"
    auto_ip: false
    security_groups: devstack2,default
  register: devstack1

- name: Add devstack server to discourse group
  add_host:
    name: "{{ devstack1.openstack.public_v4 }}"
    groups: devstackservers
  when: devstack1.openstack.public_v4 != ""

- name: Add devstack server to discourse group
  add_host:
    name: "{{ devstack1.openstack.private_v4 }}"
    groups: devstackservers
  when: devstack1.openstack.public_v4 == ""

- name: wait for ssh
  wait_for:
    host: "{{ item }}"
    port: 22
    timeout: 60
    state: started
  with_items: "{{ groups.devstackservers }}"
